/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as crons from "../crons.js";
import type * as v_user from "../v/user.js";
import type * as v_userEightsleepTokenData from "../v/userEightsleepTokenData.js";
import type * as v_userSpotifyTokenData from "../v/userSpotifyTokenData.js";
import type * as v_userTodayData from "../v/userTodayData.js";
import type * as v_userTodayDataUpdate from "../v/userTodayDataUpdate.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  crons: typeof crons;
  "v/user": typeof v_user;
  "v/userEightsleepTokenData": typeof v_userEightsleepTokenData;
  "v/userSpotifyTokenData": typeof v_userSpotifyTokenData;
  "v/userTodayData": typeof v_userTodayData;
  "v/userTodayDataUpdate": typeof v_userTodayDataUpdate;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
